type = "checkout_ui_extension"
name = "tax-calc"

extension_points = [
  'Checkout::Dynamic::Render'
]


[[metafields]]
namespace = "custom"
key = "billing"

[capabilities]
block_progress = true


# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
 [settings]
   [[settings.fields]]
   key = "label"
   type = "single_line_text_field"
   name = "Put label for field here"
   description = "Label for billing reference ID"
