type = "checkout_ui_extension"
name = "test-extension"

extension_points = [
  'Checkout::Dynamic::Render'
]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"


[settings]
   [[settings.fields]]
   key = "banner"
   type = "single_line_text_field"
   name = "Banner title"
   description = "Enter a title for the banner"
